config/routes.rb
Rainforest2::Application.routes.draw do
  
  resources :sessions, :only => [:new, :create, :destroy]
  
  resources :products do
    resources :reviews, :only => [:index, :new, :show, :create, :destroy]
  end
  
  resources :users, :only => [:new, :create]

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :description, :price_in_cents, :price_in_dollars

  validates :name, :description, :presence => true
  validates :price_in_cents, :presence => true,
            :numericality => { :greater_than_or_equal_to => 0 }

  monetize :price_in_cents, :as => "price_in_dollars", :presence => true,
           :numericality => { :greater_than_or_equal_to => 0 }

  has_many :reviews, :dependent => :destroy

end

app/models/review.rb
class Review < ActiveRecord::Base

  attr_accessible :comment

  validates :comment, :user_id, :product_id, :presence => true

  belongs_to :product
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password_digest, :password, :password_confirmation

  validates :name, :email, :password, :password_confirmation, :presence => true

  has_many :reviews

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  # GET products
  def index
    @products = Product.all
  end

  # GET products/1
  def show
    @product = Product.find(params[:id])
    @review = Review.new
  end

  # GET product/new
  def new
    @product = Product.new
  end

  # POST products
  def create
    @product = Product.new(params[:product])
      if @product.save
        redirect_to @product, :notice => "Product successfully created!"
        # redirect_to product_path => "Product successfully created!"
      else
        render :action => :new
      end
  end

  # GET products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # PUT product/1
  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(params[:product])
      redirect_to @product, :notice => "Product updated!"
    else
      render action: :edit
      # or, render :action => edit
    end
  end

  # DELETE product/1
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    if @product.save
      redirect_to products_path, :notice => "Product deleted!"
    else
      render action: :index
    end
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_filter :find_product

  def index
  end

  def new
  end

  def create
    @review = @product.reviews.build(params[:review])
    @review.user = current_user

    # or,
    # @review = Review.new
    # @review.comment = params[:review][:comment]
    # @review.product_id = params[:product_id]
    # @review.user_id = session[:user_id]
    
    if @review.save
      flash[:notice] = "Thanks for the review!"
      redirect_to @product
    else 
      flash[:error] = "There was an error saving your review"
      redirect_to @product
    end
  end

  def show
  end

  def destroy
  end

  private

  def find_product
    @product = Product.find_by_id(params[:product_id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
   
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to products_path
      flash[:notice] = "You're logged in!"
    else
      flash[:error] = "Login attempt failed"
      render :action => "new"
    end
 
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to products_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to products_path, :notice => "User successfully created!"
    else
      render :action => :new
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_flash_tags.html.erb
<% if flash[:notice]  %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>

<% if flash[:alert] %>
    <div class="alert"><%= flash[:alert] %></div>
<% end %>
  
<% if flash[:error] %>
    <div class="error"><%= flash[:error] %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rainforest Store</title>
   <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <% if current_user %>
    Hi, <%= current_user.name %>
    <%= link_to "Log out", session_path("#{current_user.id}"), :method => :delete %>
  <% else %>
    <%= link_to "Log in", new_session_path %>
    or 
    <%= link_to "Sign up", new_user_path %>
  <% end %>
  
  <%= render :partial => "flash_tags" %>
  <%= yield %>

  <p><%= link_to "Back", :back %></p>


</body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
<!-- or, form_for (Product.new) do |f| -->

<% if @product.errors.any? %>
  <div id="error_explanation">
    <h2> 
      <%= pluralize(@product.errors.count, "error") %> 
      prohibited this product from being saved: 
    </h2>
    <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>  
    </ul>
  </div>
<% end %>

<p>
<%= f.label :name, "Name" %><br>
<%= f.text_field :name %><br>
</p>

<p>
<%= f.label :description, "Description" %><br>
<%= f.text_area :description %><br>
</p>

<p>
<%= f.label :price_in_dollars, "Price" %><br>
$<%= f.text_field :price_in_dollars %><br>
</p>
<%= f.submit %>
<% end %>

app/views/products/edit.html.erb
<h1>Edit <%= @product.name  %></h1>

<%= render :partial => "form" %>
<!-- or, render 'form' -->

app/views/products/index.html.erb
<h1>Products</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td>$<%= product.price_in_dollars %></td>
        <td><%= link_to "Edit", edit_product_path(product) %></td>
        <td><%= link_to "Show", product_path(product) %></td>
        <td><%= link_to "Delete", product_path(product), 
                :method => :delete, 
                :confirm => "Are you sure?" %>
        </td>
      </tr>    
    <% end %>
  </tbody>
</table>

<p><%= link_to "Add a product", new_product_path %></p>

app/views/products/new.html.erb
<h1>Add a new product</h1>

<%= render :partial => "form" %>
<!-- or, render 'form' -->

app/views/products/show.html.erb
 <h1><%= @product.name %></h1>

<p>Description:</p>

<p><%= @product.description %></p>

<p>Price: $<%= @product.price_in_dollars %></p>

<p>
  <%= link_to "Edit", edit_product_path(@product) %>
  <%= link_to "Delete", @product, 
                  :method => :delete, 
                  :confirm => "Are you sure?" %>
</p>

<h2>Reviews:</h2> 
<% @product.reviews.each do |review| %>
  <em><%= review.user.name %>
  wrote at <%= review.created_at %>:</em>
  <p><%= review.comment %></p>
<% end %>

<% if current_user %>
  <%= render "reviews/form" %>
<% else %>
  To write a review,
  <%= link_to "Log in", new_session_path %>
  or 
  <%= link_to "Sign up", new_user_path %>.
<% end %>

app/views/reviews/_form.html.erb
<%= form_for [@product, @review] do |f| %>

  <p>
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </p>

  <%= f.submit %>
<% end %>

app/views/reviews/_review.html.erb
  <em><%= review.user.name %>
  wrote at <%= review.created_at %>:</em>
  <p><%= review.comment %></p>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/new.html.erb
<h1>Add a new review</h1>

<%= render 'form' %>

app/views/reviews/show.hmtl.erb
<h1>show</h1>
<%= @reviews %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2> 
        Uh oh,
        <%= pluralize(@user.errors.count, "error") %> 
        prevented you from signing up: 
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>  
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name, "Name" %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :email, "Email" %><br>
    <%= f.email_field :email %>
  </p>
  
  <p>
    <%= f.label :password, "Password" %><br>
    <%= f.password_field :password %>
  </p>

  <%= f.label :password_confirmation, "Password Confirmation" %><br>
  <%= f.password_field :password_confirmation %>
  </p>

  <%= f.submit %>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render :partial => "form" %>